# -*- coding: utf-8 -*-
"""第8回確認試験_うるう年判別プログラム_G241TG2002_石川遼太郎

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkerOuf2AS0MUADTfxfI_cBo-cBtTu-1

## 修正・工夫した点

1. 年の入力が4桁で、かつ1000～9999の範囲内であることを確認するバリデーションを追加しました。これにより、誤った年が入力されてもプログラムがエラーメッセージを表示し、正しい入力を促すようになっています。
2. `end`を入力することでプログラムが終了できるようにし、繰り返しうるう年を判定できるよう工夫しました。
3. プログラムが利用された回数と、判定されたうるう年の回数をカウントし、終了時に表示することで、プログラムの利用状況をわかりやすく示しています。
"""

def is_leap_year(year):
    """
    指定された年がうるう年かどうかを判定する関数。
    うるう年の条件:
        - 4で割り切れる年はうるう年。
        - ただし、100で割り切れる年はうるう年ではない。
        - 400で割り切れる年はうるう年。

    引数:
        year (int): 判定する年 (4桁の整数)
    戻り値:
        bool: うるう年であればTrue、そうでなければFalse
    """
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

print("4桁の年を入力して、うるう年かどうか判定します。'end'と入力すると終了します。")

count = 0  # プログラム利用回数のカウント
leap_year_count = 0  # うるう年の回数カウント

while True:
    input_year = input("4桁の年を入力してください (終了するには 'end' と入力): ")

    if input_year.lower() == "end":
        print(f"\nプログラムを終了します。利用回数: {count} 回")
        print(f"判定されたうるう年の回数: {leap_year_count} 回")
        break

    # 入力が4桁の数字か確認し、範囲内かも検証
    if input_year.isdigit() and len(input_year) == 4:
        year = int(input_year)
        if 1000 <= year <= 9999:
            if is_leap_year(year):
                print(f"{year} 年はうるう年です。")
                leap_year_count += 1
            else:
                print(f"{year} 年はうるう年ではありません。")
            count += 1  # カウントの更新
        else:
            print("有効な範囲（1000年から9999年）で入力してください。")
    else:
        # 入力が不正な場合のメッセージ
        print("無効な入力です。4桁の年を入力してください。")